markdown: redcarpet
permalink: /:year/:month/:day/:title/
url: http://chunyang-wen.github.io
author: chunyang-wen
pygments: false
safe: true
paginate: 16
auto: true
redcarpet:
  extensions: [fenced_code_blocks]
  render_options:

