# Site settings
title: CoolMind
header-img: "images/mountain.jpg"
tagline: "吉光片羽"
description: "If you cannot measure it, you cannot improve it."
baseurl: ""
# url: "http://azeril.me"
# url: "http://localhost:4000"
page_seq: "tools, tags,  about" # lower case, separated by ','

#url: http://chunyang-wen.github.io
url: http://chunyangwen.com
# enforce_ssl:

# About/contact
owner:
  name: "chunyang"
  email: chunyang.wen@gmail.com
  bio: "If you cannot measure it, you cannot improve it."

# Data
gavatar: https://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

#douban_username: Azeril
#twitter_username: Azeril_Lapland
github_username: chunyang-wen
#facebook_username: Azeril_Lapland
weibo_username: 老文or小文
linkedin_username: chunyang-wen-01172475
# zhihu_username: damnfish

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
  # no_auto_ids: true
  auto_ids: true
highlighter: rouge

#gems:
plugins:
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "chunyang"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# enable future docs
future: true

# Comments
#comments :
#  provider : duoshuo
#  duoshuo :
#    short_name : Azeril
#  disqus :
#      short_name : Azeril

# Analytics and webmaster tools stuff goes here
#google_analytics: UA-66863061-1
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in footer navigation
