# Site settings
title: CoolMind
tagline: ""
description: "If you cannot measure it, you cannot improve it."
baseurl: ""
# url: "http://azeril.me"
# url: "http://localhost:4000"
page_seq: "tools, archive, about" # lower case, separated by ','

#url: http://chunyang-wen.github.io
url: https://www.chunyangwen.com
# enforce_ssl:

# About/contact
owner:
  name: "chunyang"
  email: chunyang.wen@gmail.com
  bio: "If you cannot measure it, you cannot improve it."


github_username: chunyang-wen
weibo_username: 老文or小文
linkedin_username: chunyang-wen-01172475

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
  # no_auto_ids: true
  auto_ids: true
highlighter: rouge

#gems:
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-redirect-from
# - jekyll-archives
# https://jekyllrb.com/docs/permalinks/
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "chunyang"


# enable future docs
future: true
